### ISSUE TITLE
Support node v14

### ISSUE THREAD

**Issue by jsbrain** [vegardit/prisma-generator-nestjs-dto#1]
Installing the package gives me the error that it's incompatible with node < 16.3.

Is there a problem why this package doesn't work with v14 or is it just a matter of configuration?

Thanks :)

**Comment by benkroeger** [comment]
this is because TypeScript is configured to compile to ES2020 - which is fully implemented only in nodejs >= 16.3.

I think we can safely compile to ES2019 and thus work with nodejs 14.

**Comment by yassinebridi** [comment]
This would be cool to have.

**Comment by benkroeger** [comment]
released in [v1.1.1](https://github.com/vegardit/prisma-generator-nestjs-dto/releases/tag/v1.1.1)
