### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by johannesschobel** [vegardit/prisma-generator-nestjs-dto#109]
Dear all,

is this package still maintained? Latest commits are only "update deps" and no new features.
All the best,
Johannes

**Comment by benkroeger** [comment]
Since we've moved our apis to graphql, we're not actively doing any development work on this project at the moment.
We're relying on the community to provide additional features via PRs if needed.

**Comment by johannesschobel** [comment]
Thanks for clarifying. All the best
