### ISSUE TITLE
Error: spawn prisma-generator-nestjs-dto ENOENT

### ISSUE THREAD

**Issue by weihsth** [vegardit/prisma-generator-nestjs-dto#16]
Hi,

I just tried out your tool and get following Error on my windows machine after running `prisma generate`:

```Error: spawn prisma-generator-nestjs-dto ENOENT```

I tried running it in git bash, IntelliJ Terminal, CMD, Windows Terminal. Is it maybe an missing permission (I have a lokal Admin account..)? Or is my schema code wrong?

```
generator client {
  provider        = "prisma-client-js"
  output          = "../generated/prisma-client"
}

generator nestjsDto {
  provider                        = "prisma-generator-nestjs-dto"
  output                          = "../libs/shared-dto/src/test"
  outputToNestJsResourceStructure = "false"
  exportRelationModifierClasses   = "true"
  reExport                        = "false"
  createDtoPrefix                 = "Create"
  updateDtoPrefix                 = "Update"
  dtoSuffix                       = "Dto"
  entityPrefix                    = ""
  entitySuffix                    = ""
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

[...]
```

UPDATE:
I also tried it after doing this:
```
rimraf node_modules
npm cache clean --force
npm ci
```

Do you have any idea?

Regards

**Comment by benkroeger** [comment]
installing the package should create a symlink in `node_modules/.bin/prisma-generator-nestjs-dto` pointing to `node_modules/prisma-generator-nestjs-dto/dist/cli.js`.
Can you pls verify this exists?

The `provider` field in your schema tells the prisma cli which command to execute to run this generator - so basically what the error is telling you is that the cli can not span the generator process because the file doesn't exist.

**Comment by weihsth** [comment]
Hi @benkroeger ,

I had a look, and there are 3 files:
![image](https://user-images.githubusercontent.com/20488966/141154258-88f8f0ab-e3f3-48c0-8dd4-d3c46f03db14.png)

I read about running the "spawn" function with {shell: true} on windows, maybe this is not happening?

**Comment by benkroeger** [comment]
idk. I'm just providing the command - the call (spawn etc) is in the prisma cli.
Have you tried running this in a privileged mode?
I know there are other users running this on windows - so in general it seems to work. I don't have a windows machine at hand.

**Comment by benkroeger** [comment]
what happens when you call the `.cmd` file directly (not expecting the generator to actually run then because all the inputs are missing - but maybe the process starts)

**Comment by weihsth** [comment]
I can call it directly. So I try to check, if prisma@3.4.1 is the problem and get back here later.

**Comment by weihsth** [comment]
I just tried another generator to see if it' a general issue: 

```
generator jsonSchema {
  provider = "prisma-json-schema-generator"
}
```

And it worked... 🤔

```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (3.4.2) to .\generated\prisma-client in 1.34s

✔ Generated Prisma JSON Schema Generator to .\prisma\json-schema in 173ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from './generated\prisma-client'
const prisma = new PrismaClient()
```

```

**Comment by weihsth** [comment]
Good morning,

found the "problem", @benkroeger ! I had a look into the package.json of this project and saw, that node >= 14 is needed. So I just tried it with 14.18.1 and everything works. The errer message was totally misleading.

Have a reat day! Thank your for this great tool!
