### ISSUE TITLE
We want to maintain this project

### ISSUE THREAD

**Issue by ydhn** [vegardit/prisma-generator-nestjs-dto#190]
Hi, This is Jordan from @mvlchain  
We're recently using Prisma for our nestjs projects and currently we're using this library for auto-generating dtos.  
We've once reached to this project like this PR: https://github.com/vegardit/prisma-generator-nestjs-dto/pull/149  
  
Due to the stopping maintenance of this library, we currently using this package deploying to our custom set package manager,
but it would be great if our company succeeds in this project as an open source project and keep touching the community who are using this library and keep going on (Because auto-generate is always good to developers!)

**Comment by Eazash** [comment]
@ydhn Could you please publish your fork?

**Comment by ydhn** [comment]
@Eazash https://www.npmjs.com/package/@yundo/prisma-generator-nestjs-dto Here it is

**Comment by AmreeshTyagi** [comment]
Seems like it is maintained by few same contributors here in another repo.
https://github.com/botika/prisma-generator-nestjs-dto

i see more commits & it has class validator too.
