### ISSUE TITLE
Support for class-validator decoration

### ISSUE THREAD

**Issue by lodisy** [vegardit/prisma-generator-nestjs-dto#23]
Is there any way to add validator decoration in the schema file, just like [this](https://github.com/unlight/prisma-nestjs-graphql)?

**Comment by lodisy** [comment]
After looking into the docs and issues, the cli seems to have limited capability to do this.

**Comment by benkroeger** [comment]
this generator doesn't support validator annotations.

**Comment by robbievandam** [comment]
Hey @benkroeger,

Nice work in putting this together! 

I was wondering how you deal with validation as this generator doesn't support the class-validation package as mentioned.

Most people will probably opt for manual DTOs so they can set up there own swagger scheme and input validations. It really feels like this is the missing key which would make prisma the perfect orm.. 🤔

**Comment by benkroeger** [comment]
to be honest, we don't use this generator anymore. the project switched from rest to graphql - and also we're planning to move away from prisma. 
WRT validation, I like superstruct a lot.It provides superb error details and doesn't require converting pure JSON data into class instances before validation.

**Comment by ManuRodgers** [comment]
> 

Why do you guys move away from prisma?
