### ISSUE TITLE
Support for enum types.

### ISSUE THREAD

**Issue by yassinebridi** [vegardit/prisma-generator-nestjs-dto#3]
Since NestJS requires you to manually set the enum property on the `@ApiProperty`:
https://docs.nestjs.com/openapi/types-and-parameters#enums

Would it be possible to extract the enum properties from the `prisma.schema` and generate the corresponding @Api decorator like so:
- prisma.schema
```prisma
model User {
  id          String   @id @default(cuid())
  userType    UserType
}
enum UserType {
  student
  teacher
}
```
- user.entity.ts
```ts
import { UserType } from '@prisma/client';

export class User {
  id: string;
  
  @ApiProperty({ enum: ['student', 'teacher']})
  userType: UserType;
}
```

**Comment by benkroeger** [comment]
implemented in [v1.2.0](https://github.com/vegardit/prisma-generator-nestjs-dto/releases/tag/1.2.0)

**Comment by yassinebridi** [comment]
Thank you @benkroeger.
would it be possible to add  the `@ApiProperty` for entities too?

**Comment by benkroeger** [comment]
@yassinebridi can you provide a PR for that?
I don't actually see a need for decorating the prop in an entity class - as the necessary information is supposed to be extracted by TypeScript. Also, the OpenAPI explorer provides no enum specific functionality on output components.

What's missing in v1.2.0 though is the case when the enum field is a list / array

**Comment by yassinebridi** [comment]
In the OpenAPI explorer, it actually shows what kind of enum response you are supposed to get, eg:

![scr-07-15-01-PM5109](https://user-images.githubusercontent.com/18403595/125791122-d9be10dc-6620-4e8b-910b-2273578a7646.jpg)
That of course if you decorated that property in the entity class.
Currently, it just shows an empty object in that `role` field

![scr-07-15-01-PM5309](https://user-images.githubusercontent.com/18403595/125791408-70275a82-dbaa-4db2-9bf0-b0783e668421.jpg)

I can provide a PR for this if you feel like this could be useful for this library.

**Comment by benkroeger** [comment]
Sure, go ahead a propose a PR.
I was under the impression that this worked for me before... haven't verified. Maybe this is some of the magic when using [@nestjs/cli](https://www.npmjs.com/package/@nestjs/cli)

**Comment by yassinebridi** [comment]
Yep, this is supposed to work out of the box when using the cli OpenAPI plugin, as stated here:
https://docs.nestjs.com/openapi/cli-plugin#overview
```
set the type or enum property depending on the type (supports arrays as well)
```
I will check with the @nestjs/swagger repo first if this is a known issue.
