### ISSUE TITLE
Generate index.ts

### ISSUE THREAD

**Issue by timosg** [vegardit/prisma-generator-nestjs-dto#4]
Is it possible to generate a index.ts which exports all generated interfaces/types etc. ?

For example a generated file like this:

```
export * from './connect-user.dto';
export * from './create-user.dto';
export * from './update-user.dto';
export * from './user.entity';
```

**Comment by benkroeger** [comment]
atm it's not - Can you provide a PR? Happy to review it.

**Comment by yassinebridi** [comment]
Wouldn't be better to put everything in one file, like prisma does with their client.

**Comment by yassinebridi** [comment]
Wouldn't be better to put everything in one file, as prisma does with their client.

**Comment by timosg** [comment]
@yassinebridi 
i think this should then become a separate function or ?

so maybe

```
generator nestjsDto {
  provider                        = "prisma-generator-nestjs-dto"
  output                          = "../src/generated/nestjs-dto"
  outputToNestJsResourceStructure = "false"
  exportRelationModifierClasses   = "true"
  generateIndex = "true" // <---- NEW
  createMonolith = "true" // <---- NEW
  createDtoPrefix                 = "Create"
  updateDtoPrefix                 = "Update"
  dtoSuffix                       = "Dto"
  entityPrefix                    = ""
  entitySuffix                    = ""
}
```

Obviously change the option names to fit better.

i'll take a look at the source code and see what would fit in best for these cases.

**Comment by yassinebridi** [comment]
@timosg You should ve carful of having a dead zone issues between classes.

**Comment by benkroeger** [comment]
actually, as this generator is intended for nestjs, you can use 'outputToNestJsResourceStructure' to create DTOs in resource modules.
Controllers from Nest CLI generated CRUD resources will import create, update and entity classes correctly.
This is the main reason for not providing everything in one file in the first place

**Comment by 9267aakashsharma** [comment]
You can use `reExport  = "true"` to auto create an `index` file which re-exports everything.
