### ISSUE TITLE
Configurable file naming scheme

### ISSUE THREAD

**Issue by ohmree** [vegardit/prisma-generator-nestjs-dto#57]
Hi, this project looks really nice, thanks for creating it!

I've noticed that ATM the generated file names are always in `camelCase`, while I prefer `kebab-case`.

I could really benefit from an option to set the naming scheme for generated files, similarly to the one that seems to be implemented in [this generator](https://github.com/tpdewolf/prisma-nestjs-dto-generator).

Is this something that could be added?

**Comment by benkroeger** [comment]
the codebase is already prepared to support this scenario with minimal changes. The filename case transformation is abstracted in all relevant components and would only need to be replaced in a few places.

Take a looke [here](https://github.com/vegardit/prisma-generator-nestjs-dto/blob/main/src/generator/index.ts#L57).
Happy to review a PR.
