### ISSUE TITLE
Proposing syntax to reduce code boilerplate and add flexibility

### ISSUE THREAD

**Issue by sandbox-apps** [vegardit/prisma-generator-nestjs-dto#8]
The current approach was a bit verbose and easily to become complex and unmaintainable specially when there are too many fields and dto properties. As for the future prisma will also add check constraints annotation which will make more hard to read the DTO...

I have a proposed syntax where it can improve some part of the model schema
Here is the example:
```dart
enum Gender {
  male
  female
  other
}

enum Role {
  admin
  moderator
  user
}

/// @@CreateDTO(name:"User", fields: [firstname, middlename, lastname, birthday, gender])
/// @@UpdateDTO(name:"UserFullname", fields: [firstname, middlename, lastname])
/// @@UpdateDTO(name:"UserBirthday", fields: [birthday])
/// @@UpdateDTO(name:"UserGender", fields: [gender])
model User {
 id String @id @default(cuid())
 firstname String
 middlename String?
 lastname String
 birthday DateTime?
 gender Gender?

 memberships Membership[]
}

/// @@CreateDTO(name:"Group", fields: [name, description, memberships])
/// @@UpdateDTO(name:"GroupName", fields: [name])
/// @@UpdateDTO(name:"GroupDescription", fields: [description])
model Group {
  id String @id @default(cuid())
  name String
  description String

  memberships Membership[]
}

/// @@CreateDTO(name:"Membership", fields: [groupId, id])
/// @@UpdateDTO(name:"MembershipRole", fields: [role])
model Membership {
  group Group @relation(fields: [groupId], references: [id])
  groupId String

  user User @relation(fields: [id], references: [id])
  id String @id @default(cuid())

  role Role @default(user)
}
```

1. This is improves readability by decluttering field level annotating.
2. More Flexibility to customize the name of DTO and cherry pick a field for specific DTO. Handful if you have many single field update API
3. All fields for CreateDTO and UpdateDTO are group into single line "`Single Responsibility`"
4. All optional fields can be inferred by instrospecting "?" on field type

**Comment by sandbox-apps** [comment]
/// @@CreateDTO(name:"User", fields: [firstname, middlename, lastname, birthday, gender])
/// @@UpdateDTO(name:"UserFullname", fields: [firstname, middlename, lastname])
/// @@UpdateDTO(name:"UserBirthday", fields: [birthday])
/// @@UpdateDTO(name:"UserGender", fields: [gender])

Also the following would correspond to the naming configuration set on nestjs dto generator

1. CreateUserDto (src/user/dto/create-user.dto.ts)
2. UpdateUserFullnameDto (src/user/dto/update-user-fullname.dto.ts)
3. UpdateUserBirthdayDto (src/user/dto/update-user-birthday.dto.ts)
4. UpdateUserGenderDto (src/user/dto/update-user-gender.dto.ts)

**Comment by sandbox-apps** [comment]
Notice the syntax here in CreateDTO where we include relationship
```dart
/// @@CreateDTO(name:"Group", fields: [name, description, memberships])
/// @@UpdateDTO(name:"GroupName", fields: [name])
/// @@UpdateDTO(name:"GroupDescription", fields: [description])
model Group {
  id String @id @default(cuid())
  name String
  description String

  memberships Membership[]
}
```
by default it will just create the Create input for relationship
If we want to achieve a CreateOrConnectDto maybe it could do something like this

```dart
/// @@CreateDTO(name:"Group", fields: [name, description, memberships], connect: [memberships])
/// @@UpdateDTO(name:"GroupName", fields: [name])
/// @@UpdateDTO(name:"GroupDescription", fields: [description])
model Group {
  id String @id @default(cuid())
  name String
  description String

  memberships Membership[]
}
```
see syntax `connect: [memberships]`

**Comment by sandbox-apps** [comment]
I believe this can still achieve what current syntax can do but in more readable and easy way.

**Comment by timosg** [comment]
i think the problem with this approach is the obligation to add an annotation to each model. Generating a DTO with the current approach will also work without any notation. So maybe convert the functionality for the current approach to a model based annotation.

```scala
/// @@DtoEntityHidden(fields: [password])
model User {
  id String @id @default(cuid())
  name String
  password String
}
```

i don't know how this works best for the other annotations, but this would be a spontaneous idea of mine now.

do not misunderstand I like your proposal, but it would be great if we have a solution from both worlds.

**Comment by sandbox-apps** [comment]
@timosg, I believe for entity hidden approach will not be a problem for future but as of now. I have seen that prisma team has tackling also the issue about what you shown in your comment. I believe there will be a annotation for that by making by prisma itself..

And honestly right now I dont know why we still need to generate the entity? when prisma already generate it via model. I would love to see a use cases where generating entity is okay so I can learn.

I still believe annotation per model is handy than per per bunch of fields

> So maybe convert the functionality for the current approach to a model based annotation.

I dont know what you mean by this. But thats what I wanted it too :)

Maybe if we combine are idea we can do like this.
```dart
/// @@CreateDto(name: "User", hidden: [password])
model User {
  id String @id @default(cuid())
  name String
  password String
}
```
then we should get a `CreateUserDto` without a password field. The inverse of when you specify `fields`.

**Comment by sandbox-apps** [comment]
Whatever approach you may choose they should have the same output

**Comment by timosg** [comment]
I like this approach, but in the end the maintainer must decide. I also don't know how active he is because this is obviously a very small project.

**Comment by sandbox-apps** [comment]
Yes, you're right mate. I'm just trying here. If ever got his attention or will not. It still fine :)

**Comment by benkroeger** [comment]
Thanks for this great proposal and discussion.
I personally like the approach to annotate individual properties rather than the entire model - as it is easier to overlook / forget adding a new property to the model-level annotation. On a property-level annotation, fields get added automatically - action only required if you want to handle the field in any special way.

However, I also agree that the current design of multiple annotations looks cluttered.
So this is what I'd go for in terms of de-cluttering:

```prisma
model Group {
  id String @id @default(cuid())
  /// @DTO({ create: 'required', update: 'optional', entity: 'hidden' })
  password String
}
```

Obviously, it needs some thoughts with regards to relations (onCreate, onUpdate / canCreate, canConnect)

**Comment by sandbox-apps** [comment]
I'll guess I will lose here because you prefer that. Haha :D

My use cases was like this
```ts
/// @@CreateDTO(name:"Group", fields: [name, description, memberships], connect: [memberships])
/// @@UpdateDTO(name:"GroupName", fields: [name])
/// @@UpdateDTO(name:"GroupDescription", fields: [description])
model Group {
  id String @id @default(cuid())
  name String
  description String

  memberships Membership[]
}
```
Where you just pass what is required values here...

I guess your approach was you just have the normal crud endpoints...
In ur example the problem with that is sometimes you only want to update the fullname and not password and sometimes you want to update password and the fullname so password is required now and fullname is optional

This will be the endpoint for different DTO
/users/:id/fullname (Patch) -> Password is optional here
/users/:id/change-password (Patch) -> Password is required here

**Comment by benkroeger** [comment]
you can do 

/users/:id (Patch)

and send a json object that has all the fields you want to update.

Also, since this generator creates DTOs and not Controllers, you can tailor the results however you like to match your controller needs. (e.g with [MappedTypes](https://docs.nestjs.com/openapi/mapped-types)

**Comment by sandbox-apps** [comment]
But this is exactly what were trying to avoid `/users/:id (Patch)` in the first place 😅
But yeah you're right here -> https://docs.nestjs.com/openapi/mapped-types
Customize and omit fields will be the solution here. Thanks.
