### ISSUE TITLE
decorate class props with @ApiProperty

### ISSUE THREAD

**Issue by goemen** [vegardit/prisma-generator-nestjs-dto#9]

**Comment by benkroeger** [comment]
Since there is no description to this issue whatsoever, the following response answers a best-guess understanding of the 'question':

Please use [NestJS CLI](https://docs.nestjs.com/openapi/cli-plugin). It adds the `@ApiProperty` decorator at runtime

**Comment by stuckinaboot** [comment]
I believe this issue is in reference to the fact that if you use the following in your main.ts, then any fields you don't explicitly decorate with some annotation will be stripped (not included) when being passed in from some client that is calling the endpoint with those field. I tried this myself and this seems to be happening

```
app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
    })
  );
```

**Comment by benkroeger** [comment]
I didn't verify this - but if what you're saying is what's happening, this looks more like a disconnect between global validation pipe's whitelist feature - and auto-annotations via nest cli.

On  the other hand - I'm happy to review a PR that allows decorating all DAO and model fields via an additional generator config property

**Comment by stuckinaboot** [comment]
I'll take a stab at this

**Comment by stuckinaboot** [comment]
Actually, upon an attempt at this, I decided I don't need this functionality. However, if somebody else does, they are welcome to continue from my fork https://github.com/stuckinaboot/prisma-generator-nestjs-dto. Note that it's on `ApiProperty` that's required, it's some class validator (such as `Allow` which is the no-op validator) in order for the field to pass the whitelist

**Comment by Jaikant** [comment]
> Since there is no description to this issue whatsoever, the following response answers a best-guess understanding of the 'question':
> 
> Please use [NestJS CLI](https://docs.nestjs.com/openapi/cli-plugin). It adds the `@ApiProperty` decorator at runtime
@benkroeger  Thanks this comment helped me!

**Comment by clayrisser** [comment]
@Jaikant how do you use nestjs cli with babel?
